# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SearchZmap
                                 A QGIS plugin
 住宅地図検索プラグイン
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-01
        copyright            : (C) 2021 by orbitalnet.inc
        email                : who@orbitalnet.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SearchZmap class from file SearchZmap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .search_zmap import SearchZmap
    return SearchZmap(iface)
